# Generated by Django 5.1.7 on 2026-02-20 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='descricao',
            new_name='description',
        ),
    ]
